<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Gourab-Laptop" failures="1" tests="8" name="demo.QtripTests" time="137.794" errors="0" timestamp="31 May 2025 13:59:39 GMT">
  <testcase classname="demo.QtripTests" name="qtrip_non_functional_005" time="10.739"/>
  <testcase classname="demo.QtripTests" name="qtrip_non_functional_004" time="6.694"/>
  <testcase classname="demo.QtripTests" name="qtrip_ui_002" time="50.811"/>
  <testcase classname="demo.QtripTests" name="qtrip_non_functional_003" time="5.619"/>
  <testcase classname="demo.QtripTests" name="qtrip_ui_001" time="18.361"/>
  <testcase classname="demo.QtripTests" name="qtrip_non_functional_002" time="15.650">
    <failure message="The following asserts failed:
	expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at demo.QtripTests.qtrip_non_functional_002(QtripTests.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- qtrip_non_functional_002 -->
  <testcase classname="demo.QtripTests" name="qtrip_ui_003" time="25.876"/>
  <testcase classname="demo.QtripTests" name="qtrip_non_functional_001" time="4.044"/>
</testsuite> <!-- demo.QtripTests -->
